django/config/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webtoon.urls')),
]

django/webtoon/urls.py
from django.urls import path
from . import views

app_name = 'webtoon'
urlpatterns = [
    path('', views.webtoon_list, name='webtoon-list'),

    path('<int:pk>/', views.webtoon_detail, name='webtoon-detail'),
]

django/webtoon/models.py
import re

import requests
from bs4 import BeautifulSoup
from django.db import models


class Webtoon(models.Model):
    webtoon_id = models.CharField(max_length=100)
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

    def get_episode_list(self):

        url = 'https://comic.naver.com/webtoon/list.nhn'
        params = {
            'titleId': self.webtoon_id,
            'page': '1',
        }
        response = requests.get(url, params)
        soup = BeautifulSoup(response.text, 'lxml')
        tr_list = soup.find('table').find_all('tr', class_='')

        for tr in tr_list[1:]:
            episode_id = re.search(r".*'(\d+)", tr.select_one('td:nth-of-type(1) a').get('onclick')).group(1)
            # exurl_thumbnail = tr.select_one('td:nth-of-type(1) a').get('href')
            title = tr.select_one('td:nth-of-type(2) a').get_text(strip=True)
            rating = tr.select_one('td:nth-of-type(3) div strong').get_text(strip=True)
            created_date = tr.select_one('td:nth-of-type(4)').get_text(strip=True)

            if not self.episode_set.all().filter(episode_id=episode_id).exists():
                episode = self.episode_set.create(
                        episode_id=episode_id,
                        title=title,
                        rating=rating,
                        created_date=created_date
                    )


class Episode(models.Model):
    webtoon = models.ForeignKey(Webtoon, on_delete=models.CASCADE)
    episode_id = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    rating = models.CharField(max_length=100)
    created_date = models.CharField(max_length=100)

    def __str__(self):
        return '{} | {} | {} | {}'.format(
            self.episode_id,
            self.title,
            self.rating,
            self.created_date
        )

django/webtoon/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import Webtoon


def webtoon_list(request):

    webtoons = Webtoon.objects.all()
    context = {
        'webtoons': webtoons,
    }
    return render(
        request=request,
        template_name='webtoon_list.html',
        context=context,
    )


def webtoon_detail(request, pk):

    webtoon = Webtoon.objects.get(pk=pk)
    webtoon.get_episode_list()
    context = {
        'webtoon': webtoon,
    }
    return render(
        request=request,
        template_name='webtoon_detail.html',
        context=context,
    )

django/templates/webtoon_detail.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Webtoon</title>
</head>
<body>
    <div class="header">
        <div class="container">
            <h1><a href="">{{ webtoon.title }}</a></h1>
        </div>
    </div>
    <div class="container">
        <ul>
        {% for episode in webtoon.episode_set.all %}
            <li>{{ episode.episode_id }} | {{ episode.title }} | {{ episode.rating }} | {{ episode.created_date }}</li>
        {% endfor %}
        </ul>
    </div>
</body>
</html>

django/templates/webtoon_list.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Webtoon</title>
</head>
<body>
    <div class="header">
        <div class="container">
            <h1><a href="{% url 'webtoon:webtoon-list' %}">Webtoon List</a></h1>
        </div>
    </div>
    <div class="container">
        {% for webtoon in webtoons %}
        <ul>
            <li><a href="{% url 'webtoon:webtoon-detail' pk=webtoon.pk %}">{{ webtoon.title }}</a></li>
        </ul>
        {% endfor %}
    </div>
</body>
</html>